// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef gui_fltk_tab_h
#define gui_fltk_tab_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *fltk_main_window;
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *main_fltk_tab;
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
extern Fl_Input *chainDir_Filename;
#include <FL/Fl_Button.H>
extern Fl_Button *chainDir_Open;
extern Fl_Button *calcChain_Start;
extern Fl_Button *calcChain_Pause;
extern Fl_Button *calcChain_Stop;
#include <FL/Fl_Box.H>
#include <FL/Fl_Progress.H>
extern Fl_Progress *calcChain_ProgressPart;
extern Fl_Progress *calcChain_ProgressFile;
#include <FL/Fl_Output.H>
extern Fl_Output *calcChain_speed_output;
extern Fl_Input *chainFile_Filename;
extern Fl_Button *chainFile_Open;
extern Fl_Input *rbtDir_Filename;
extern Fl_Button *rbtDir_Open;
extern Fl_Progress *addRainbowTable_ProgressFile;
extern Fl_Button *addRainbowTable_Merge;
extern Fl_Button *addRainbowTable_Stop;
extern Fl_Input *searchCrypt8_Filename;
extern Fl_Button *searchCrypt8_Open;
extern Fl_Input *searchCrypt8_PID;
extern Fl_Input *searchCrypt8_PL_size;
extern Fl_Input *searchCrypt8_File_limit;
extern Fl_Button *searchCrypt8_Start;
extern Fl_Button *searchCrypt8_Stop;
extern Fl_Progress *searchCrypt8_ProgressFile;
extern Fl_Input *searchCW_Crypt8;
extern Fl_Button *searchCW_Open;
extern Fl_Input *searchCW_RBTDir;
extern Fl_Button *searchCW_Start;
extern Fl_Button *searchCW_Stop;
extern Fl_Input *searchCW_CW;
extern Fl_Box *about_label;
extern Fl_Box *about_logo;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *output_console;
#if defined(__FLTK_TAB__)
void cb_open_chain_dir(Fl_Widget *w);
void cb_calc_chain_start_btn(Fl_Widget *w);
void cb_calc_chain_pause_btn(Fl_Widget *w);
void cb_calc_chain_stop_btn(Fl_Widget *w);
void cb_open_chain_file(Fl_Widget *w);
void cb_open_rainbow_table_rbt_dir(Fl_Widget *w);
void cb_calc_rainbow_table_merge_btn(Fl_Widget *w);
void cb_calc_rainbow_table_stop_btn(Fl_Widget *w);
void cb_open_ts_file(Fl_Widget *w);
void cb_calc_search_crypt8_start_btn(Fl_Widget *w);
void cb_calc_search_crypt8_stop_btn(Fl_Widget *w);
void cb_open_search_cw_rbt_dir(Fl_Widget *w);
void cb_calc_search_cw_start_btn(Fl_Widget *w);
void cb_calc_search_cw_stop_btn(Fl_Widget *w);
Fl_Double_Window* create_fltk_gui();
#endif
#endif
